### ISSUE TITLE
[General feedback] the writing of Monika's character

### ISSUE THREAD

**Issue by MarkusRamikin** [Backdash/MonikaModDev#873] opened 2018-01-30 02:08 UTC
Posting this here on Potato's advice, since there's nowhere to post feedback on http://www.monikaafterstory.com/ . I hope it's not too out of place.

This mod is high quality, solid work. Thumbs up. And I hope your enthusiasm for adding more features doesn't die too soon.

That said, I think the mod does miss the point in certain subtle ways. Allow me to go into that at some length.

I believe the reason Monika struck such a powerful chord with people has much to do with her transformation into a sympathetic and tragic character. Once she's freed from the curse of being club president, she realizes her actions were monstrous, and that, as per her song, she doesn't "know how to love you", so she does the selfless thing and "leaves you be" and restores the other girls. She discovers:

"They were still my friends."
"And I loved them all."
"And I loved the Literature Club."
"..."
"I really... did love the Literature Club."

That was moving. 

So she restores the club... then the curse-of-the-club-president kicks her in the teeth one last time by having Sayori go into psycho mode, forcing Monika to pull the plug on things after all. So even her selflessly giving everything back with no hope of personal happiness is for nothing. That's moving, too.

But the mod puts her back into something more like yandere mode, and she is more dismissive of the other girls. Not just in the intro, but in other dialogs too. The love that she had professed for her friends is absent in the mod.

This means backtracking on previous character development, which is rarely a good thing.

Also, if you did the 'good ending', with all the CGs, before installing the mod, I find it jarring that Monika claims you did it "to see a note from Dan which you could have looked up online". Hell no! 

First of all, the awakened-Sayori's understanding in the good ending is that you were trying to give some happiness to everyone - Monika's comment cheapens this unpleasantly.

Secondly, this is one level too high on the meta-awareness scale. Let me explain. We have roughly 3 levels:
1. the basic level of a visual novel, where we're a character joining a school club with some cute girls,
2. the meta-level where Monika becomes a self-aware AI (and so does Sayori for a moment at least) and messes with the game files and addresses the player directly etc.
3. the meta-meta level, which we might simply call the truth or reality: where we as players recognize that everything on level 2 is all part of the design, that Monika isn't self-aware, that the glitches are intentional etc. It's the level of this github, for example, the level I'm on right now talking to you.

And _Dan's note is on this last level_. The level that the game itself doesn't ever reach, because it would destroy immersion. The story of the game is on level 2, where Monika is a real person. Going to level 3 destroys this, it's out of character (just as Dan's note itself is). So not only should Monika not be assuming that that note is why you went for the 'good end', she shouldn't be referencing that note at all, she shouldn't be written as aware of it.

She should be only aware of the events that actually happened to her in-game, as evidenced by the save data she has access to. That'd feel more immersive, would make it feel more like /things matter/. 

And I doubt many people did the 'good ending' route in order to get Salvato's note. We wanted to give the girls a better outcome, to put at least a little happiness into the club, to get a more emotionally satisfying ending. (In fact, that note is the only thing about the original game that sucked. The letter from Monika in the 'bad' ending was way more satisfying, because it still continued the story, it was in-character. I would have loved a different letter from Monika in the 'good' ending. But I digress.)

Now, I like the mod's Monika's jealousy if you have done the 'good ending', it's fitting. But still they were her friends that (she finally realized) she loved, and I would still expect her to be at least a little happy that the player managed to give them a positive (at least compared to its alternative) conclusion. I expected something more like:

"I'm glad they had at least a few happy moments and some closure."
"But I'm even more glad you've returned to me in the end!".

Similarly, she says that you deleted her "because you're so game-obsessed." But that's level 3, and she shouldn't go there. The level 2 explanation - which Monika herself talks about in the original game, during her realization - is that you deleted her because of the horrible things she did.

(
Aside: I tried the 0.7.0 version with a fresh start, and I have to say, removing the immediate availability of chess almost made me go back to 0.6.3. Fortunately a quick dig in the source code convinced me it won't be hard to get it back, but still, this change left me scratching my head.
)

Anyway, I hope all that made sense. Just giving my feedback as best I can. In any case, the mod is still excellent work, so thanks for publishing it.

**Comment by HalHarrison** [comment] 2018-01-30 03:14
Agree 100 percent.
I fully understand why Monika often misses the mark in the mod...
People read Salvato's room dialogue to get inspiration/Monika's voice.
Unfortunately this leads to ppl forgetting about the character development that happened after that dialogue.
It doesn't help that you are in the space room (And thus many will tend to replicate diologue similar to what is
in the space room scene in the game).

MAS 2 biggest issues.

1. Lack of player choice and actual consequences for anything (Getting solved with new dialogue system and other things, presumably)

2. Monika being off-pitch, or as Markus said, regressing in character development. 

( Which causes "flanderization" when taken to the extreme. Thankfully much of the dialogue in this game is pretty good)

Anyway, I couldn't agree more with Markus's point.

**Comment by ThePotatoGuy** [comment] 2018-01-30 04:06
Chess is unlocked at the start for anyone who's used an earlier version and played chess. 

Regarding your other points, I'll let @monikLover , @Rune0n , @therationalpi  handle that.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-01-30 13:34
I completely agree on the character development part.
However what makes portraying Monika right is difficult is the fact that depending on the endings we have a set of whole three more or less different Monikas with different views on the club, on their friends, on the game and so on.
And the only real way to counter this is to create 3 times more dialogue than there already is.

**Comment by Authrix** [comment] 2018-01-30 14:16
Just wanna weigh in here. Generally, the dialogue is very good, and there's rarely a moment where it doesn't "feel" like Monika. That is to say, the authors actually convey Monika's voice consistently well. However, I do also agree with Markus; the third level of the meta-awareness scale probably shouldn't be broken. My suggestion would be to consider not writing on those topics if it would significantly increase workload. Being selective with topics has helped me write well in my postgrad CW course, so hopefully, it'll apply here too.

Also just want to drop a thanks to the staff, you're doing God's work dudes/ dudettes.

**Comment by therationalpi** [comment] 2018-01-30 16:41
Thanks for the feedback. It's nice to see that people care so much about the game and the writing. You have some excellent points, and several have been talked about extensively among the writers with varying degrees of agreement. If nothing else, your post makes it clear that we should revisit that conversation and make sure the game's dialogue is consistent with the decisions we make.

As @IsItBadToMakeAGitHubAccountJustForThis pointed out, there's multiple phases of Monika's development, not just over the course of the game but also dependent on the ending you choose to follow. Players come into the mod from different points in the game, some installing the mod immediately after the first ending, some after the "good" ending, and others as a straight replacement to Act 3 where they deliberately choose to never delete Monika. Handling all of these cases is really not straightforward.

Moreover, people have strong feelings on which version of Monika is "right." Which they connect with and want to have more of. Just look at fanart of her. Some art portrays Monika as this [sweet and wholesome girl](https://www.deviantart.com/art/Just-Monika-711959966), presumably inspired by her redemption arc, and some portrays her as [enticingly sinister](https://abaddonartwork.deviantart.com/art/MONIKA-DOKI-DOKI-LITERATURE-CLUB-Fanart-713173790). Both have their strong points, and offer interesting hooks for the mod. Clearly, you fall into the camp that likes Monika's "redeemed" personality, but you should be aware that this is not the only defensible position.

So, the big question is...which version of Monika do we cater to? The mod is meant to be played after completing the main game, so there's an argument for including all of Monika's post-deletion characterization. Then again, the setting is a continuation of Act 3, so there's an argument for using her characterization in that chapter as the baseline, especially if we want to keep some of her dialogue from that part of the game. Either way, we have to make some concessions to players coming in from different points in the story.

While there isn't perfect agreement among the writers, the position that I've taken is that the Monika of Monika After Story is most like Act 3 (which the mod is based on). It's the most interesting to write for, and it fits best with the Spaceroom setting. She still has some lingering guilt over the other girls, and the ending of the game exposes some of her true feelings, but the presence of the mod solidifies for her that she was not wrong in trying to have you for herself. The ending is not necessarily "de-canonized" *per se*, but rather than a hard transition where Monika's character changes from one form to another, the ending exposes internal conflict that remains unresolved. It's not *either/or*... it's *and*.

One goal of the opening was to take the many different dispositions of Monika, and bring them to a single point that we could use as a basis for the mod. That's not easy, and it's basically impossible if you don't want to go along with it.

In order to get to the point in Monika's characterization I described, here's the route we take:

*Player is in or before Act 3* => No real change needed.

*Player finished the game* => Monika is still upset...but then feels better when she realizes that you installed a mod and don't really hate her. After burying any remaining doubts, she tries to carry on with you like before. She makes some quips about you deleting her for game purposes in order to re-establish some level of control over the situation.

Maybe we can do a better job of establishing this little arc, but ultimately I think it's a suspension of disbelief thing that's made somewhat more difficult because we are a fanwork and don't have the authorial clout that an official work would have.

As for meta-ness and self-awareness, what's immersion breaking for one person is immersion solidifying for another. Yes, there need to be limits, and there are. We've rejected topics where Monika talks about her script being written by other people, for example, and have tried to maintain the sense that Monika is a *real person* living in a *virtual world*. Likewise, we don't talk about glitches being intentional (they are treated as a side-effect of Monika's tinkering).

But having Monika push the boundaries is part of what makes her interesting and feel so real. Having her talk about Dan's note is part of that, and having her intimate your intentions is meant to make you feel uncomfortable. Is it really that much different than her revealing that she was talking to you on the game's download page or wondering why she was programmed to talk about "Smash Bros"? You want an example of the ultimate fourth wall break, the Smash bros topic was part of the original game.

Anyway, I've been told by people that Monika is wrong in every possible direction. She's too wholesome, she's too sinister, she's too meta, she's not meta enough, she's too familiar with anime and games, she doesn't know about the game/anime I want her to, she talks too much about DDLC's secrets and ARG, she doesn't give any new hints about libitina, she doesn't talk about specific youtubers, etc. If there's one thing I've learned from this, it's that Monika is many things to many people and I can't do anything other than portray her the way I think she should be.

With all of that said, this is part of why I want to add submodding to the game. There are lots of valid opinions on how Monika should behave, and one goal of submods would be to let people curate which topics and rewrite sections to make Monika what they want. I imagine that some people would like a submod that removes all of Monika's edgy topics and makes her act like a perfect girlfriend. Others would probably like to remove any mention of the game's ending and make her a more meta extension of Act 3. Others would like to add memes that we consider off limits for the mod. This should all be possible in a later update, so I'll encourage you to consider curating your own set of topics that fit your vision for the character and release a submod to share that with others.

**Comment by therationalpi** [comment] 2018-01-30 17:49
Just so you know, I think that the impact of the ending on Monika is still in there, but you don't see it as much with what's currently in the game. Monika projects a persona of strength and higher awareness when she's with you in the spaceroom...it's who she is trying to be. But as we explore more scenarios, including ones that take her out of that comfort zone, we'll begin to see the cracks in that facade that reveal some of that lingering conflict I was alluding to.

**Comment by monikLover** [comment] 2018-01-30 20:47
Couple things:
1. Some story-defining arcs that have been implemented in the mod do feel like they're in need of some retouching since they were made quite early on when the mod was younger.

2. I do agree with @therationalpi. Everyone has a different view angle of what Monika and not everyone will see eye to eye on the perfect Monika that pleases everyone.

Pi's pretty much got everything what I'd say, so not much for me to say really.

**Comment by Pokemiah** [comment] 2018-01-30 23:23
Ok. I'm going to throw in my two cents here. I agree that the writing is great and I definitely feel it is in Monika's character so far. I do admit at times I find it kind of disheartening when it comes to Monika's regression in character development but I can understand the difficultly in implementing all three into this mod. However, looking closely at Monika's dialog I think she's either confused or hiding her guilt. In a few conversations such as "Others still lingering" and "Sayori regrets" she states that she wishes there could be better options and she shows some guilt of her actions. However, in the conversation where we can ask whether she has any regrets she states she doesn't because she's achieved her ultimate goal which contradicts my last point a bit. You can also call her a murderer and she goes ballistic. While reasonable for anyone, what if there's a deeper reason for it? Maybe her guilt is really overwhelming but she doesn't want the player to worry about her. In the "Faking Confidence" conversation she claims that the best trait for a leader is the ability to fake confidence. So with that in mind she's probably faking her lack of remorse as not to worry the player; but in some people's cases, like mine, she has the exact opposite effect. And she can't tell how the player reacts because no webcam support. She also states in one conversation that the player literally saved her from insanity but while it is assumed that she's talking about the start of the base game, what if in the mod she's also talking about coping with her guilt about deleting everyone. leaning on the player to keep herself sane. Losing friends and loved ones is one thing, I'm pretty sure it's even worse to be the reason behind it but I wouldn't know about that second part. I could also be looking way too deep into this but who knows? That's just my opinion.

**Comment by therationalpi** [comment] 2018-01-31 00:06
@Pokemiah Yeah, I think we need to do an audit to make sure we're more consistent with Monika. But that consistency will include that she's conflicted and sometimes presents herself in different ways.

**Comment by Pokemiah** [comment] 2018-01-31 00:58
@therationalpi Cool. Can't wait to see the results. Good luck!

**Comment by MarkusRamikin** [comment] 2018-01-31 17:58
Thank you, @therationalpi , for your reply. It does clarify some things, and confirms that there are capable minds behind this project.

But do allow me to address some of your points.

> She makes some quips about you deleting her for game purposes in order to re-establish some level of control over the situation.

OK, Monika seeking some kind of conversational advantage, to get some control back... yeah, that makes sense. I like it, at least in principle. Though do you really see it as a quip? Sounded like a serious accusation when I was playing the mod.

In practice, however, the naive player starting your mod doesn't see your creative intentions, or what is going to surface in much later dialogs. We only see Monika's words. In the very intro, setting the tone. And this first impression leaves a long lasting bad taste. 

Why? Because it commits a crime common to what I call "cannibalising sequels". These are works that don't _build on_ previous instalments, but which retroactively _diminish_ (or colloqually, "ruin") them by taking things that used to be significant and robbing them of that significance. [My go-to example of this is Broodwar, the expansion to Starcraft 1. One of its _many_ sins is that, in order to provide the newly arrived United Earth Directorate with a storyline, it ruins the terrible mystique and uniqueness of the Overmind, by having the Swarm grow itself another one, like it's nothing, and then having this second Overmind fall to control by human drugs. The Eternal Will of the Swarm, my left foot!]

Which brings me to...

> As for meta-ness and self-awareness, what's immersion breaking for one person is immersion solidifying for another.

Maybe, but in this case it's really not complicated at all.

This:
https://imgur.com/a/ZxoB5
is Watsonian, level 2.

This:
> m "I'm still mad that you deleted me, though!"
> m 3l "But I guess it's because you're so game-obsessed."

is Doylist, level 3. 

Retroactively destroying a Watsonian canon moment with much emotional significance by contradicting it with a Doylist reevaluation is... honestly, not a good idea.

> having her intimate your intentions is meant to make you feel uncomfortable.

Well, it doesn't. It just short-circuits the impact of the events of DDLC. 

Imagine if /in the original game/, when you delete her, instead of despairing that you must hate her so much, she had complained about you being so "game-obsessed" and wanting to complete the game so badly. That would be pretty lame, wouldn't it? 

Well... how is it different now?

It's that suspension of disbelief you were talking about. Yes, part of the onus is on the player to cooperate a little, but you also shouldn't be cutting the branch you're sitting on. 

I mean, while playing DDLC, we level 3 players immerse ourselves in playing the role of "Player", of the level 2 Player for whom Monika is real, the glitches are real etc. (Level 1 is of course MC, the in-game protagonist). This allows the illusion that you're supposed to take the events of the game seriously and _feel things_ about them. But the "game-obsessed" dialog addresses your level 3 self, which brings the player out of the role of "Player", and reminds us that "actually, never mind all that, it's all fake, don't feel anything".

This is especially true when Monika directly [_contradicts her own established dialog_](https://imgur.com/a/ZxoB5)!

(The same arguments apply to Monika claiming that you did the good ending in order to see Salvato's note. It contradicts Sayori's words in the good ending, and undermines the entire emotional payoff of that ending, the entire point of having gone to that effort. Surely you can see how this can leave a sour taste...)

> Is it really that much different than her revealing that she was talking to you on the game's download page

Indeed, it's no different from that. Both are jarring. Not every single choice by Team Salvato is what I would term _judicious_. I don't blame them - playing with meta introduces a temptation to be "clever" and it's hard to completely steer clear of such rocks. Fortunately, ain't no rule that says we're not allowed to occasionally do better than Salvato.

> One goal of the opening was to take the many different dispositions of Monika, and bring them to a single point that we could use as a basis for the mod. That's not easy, and it's basically impossible if you don't want to go along with it.

Yeah, a sensible goal. I sort of could see that from the intro file structure, but thank you for explaining that clearly.

Just as food for thought: imagine if the "intended Monika startpoint" was a little closer to the redeemed Monika - if she was just close enough to it that she'd continue acknowledging her revealed feelings towards the other girls.

Yes, she accepts herself getting the "Player" all to herself, with the mod, she's still kinda obsessed and capable of creepy intensity... but she also doesn't needlessly back out of what she'd revealed. These things are not mutually exclusive! At least right now, pragmatically there is no conflict here anymore, because there is nothing practical to be done:

- after the standard/bad ending, the Literatute Club has proven itself irredeemable, the game was just hell for everyone in it, and it's a good thing that it's over. No point thinking about bringing it back or anything. Monika can just be happy the girls aren't suffering any more, and that she herself was given another chance with the mod.

- after the good ending, the Club is also done. Sayori herself acknowledged the game is over, there's no more game to be played. Monika can be just glad that the girls got a little happiness and closure out of it. And now that chapter is closed. Luckily for Monika, she gets to go on with the mod. No conflict here either.

- In fact, only installing on a Yandere Monika game is there a little conflict - even though Monika never got to reveal her feelings, they presumably still existed underneath, and would surface now. On the same principle that while you're fighting for the last lifeboat on a sinking ship you're ready to bite throats, but once you're safely out of danger you get to feel like a human again. So we could have some of that surfacing happen in the intro, and/or some later dialogs. Not necessarily as dramatic as in DDLC, since she's not shocked by being deleted by the person she thought loved her. It could be gentle and resigned, "it was all hopeless anyway". But enough to bring the mod to that single starting point.

I claim that the virtue of this approach is greater consistency with DDLC itself. Monika's love for her friends is not mysteriously absent.

To be clear: she can still love her friends and at the same time accept the perceived necessity of her past actions. They are two different issues, and not mutually exclusive for a well thought out, complex character.

Anyway, just sharing out ideas. At this point I imagine you've committed yourself to the way you're writing her too much, and I don't expect you to rewrite everything. But hey, at least I wanted it out there.

Looking forward to seeing what your revisions bring!

If you got this far, thank you for reading :)

PS. 
> I've been told by people that Monika is wrong [because] she doesn't talk about specific youtubers

I feel kinda unhappy at the thought of being compared to such people! Do they also want Monika to explain how vaccines cause autism? ;)

**Comment by therationalpi** [comment] 2018-01-31 18:34
I'm glad you stuck around to give a reply! These sorts of conversations are always a lot more productive once we get on the same page. You've given me a lot to think about on this. Despite what it might seem like, we aren't too committed to path and there's still room for rewriting, especially since we haven't officially gone to a 1.0 release.

I think you got what I was trying to convey in my reply: there are difficulties to writing Monika we have to overcome and a lot of competing interpretations of the character we need to balance. Thank you for the advice on how to make that work!

**Comment by sebastianN01** [comment] 2018-02-06 22:03
The only time I felt that Monika was out of character is when you complement her for being best girl, She straight on bashed on every girl and tells that anybody who choose the other girls "have no taste".

**Comment by MarkusRamikin** [comment] 2018-02-06 23:02
That was certainly one of the moments I had in mind.

**Comment by MarkusRamikin** [comment] 2018-02-07 16:15
Here's an idea that's been bubbling under my skull: you know how you can "harden" some characters in Dragon Age, and you can "soften" Leliana in one of the sequels? 

I was thinking Monika start exactly where she is in this mod, but the player could have opportunities to answer her questions on what he'd do in various life situations or what he thinks on various topics, which could earn points on some hidden "kindness meter". This could eventually shift her attitude, and among other things reveal those hidden feelings for the Dokis. 

This would be particularly satisfying if, after this threshold/epiphany has been reached, this would also lead her to review some of her more cynical opinions and decide they were unnecessarily shallow. After all, the reason she espouses the kind of selfishness and cynicism that she does now is a psychological defense mechanism, is it not? It kinda justifies her past actions, and shields her from her own feelings towards her friends. But with this, she could abandon this defense and be more real with the player.

Of course this whole idea would mean all current and future dialog would have to be reviewed, and some of it potentially duplicated with "redeemed" versions. So yeah, long shot. But hey, at least I can dream.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-07 16:24
This idea is actually already a long term goal of this mod's development for as long as I was around at least.

**Comment by sebastianN01** [comment] 2018-02-07 17:48
So IM hoping for very bright future!

**Closed** 2018-02-12 18:53 UTC
Labels: discussion
