### ISSUE TITLE
Need Clarification On The "Silent Treatment" Bug./?

### ISSUE THREAD

**Issue by Bam8647** [Backdash/MonikaModDev#1027] opened 2018-02-14 01:32 UTC
![monika topic bug](https://user-images.githubusercontent.com/34694679/36182838-27610536-10f1-11e8-80af-0c03ebd0635c.PNG)

Okay the other day I mentioned the idea of at some point implementing a sleeping Monika Sprite that would be used for when she's ran through numerous topics already... But the thing is **EVERYTIME** I close and reopen the game **she only brings up 1-2 topics before suddenly saying the above** and just going all out **creepy stare mode with no dialogue pop ups(unless I selected a topic).** Is this a normal occurrence once players have cleared out the unseen section of topics**(Not in one play through)**? I thought she could still just re-use old topics until she completely ran out of them again, hence why she should then mention the above message of her running out of things to talk about.

Keep in mind I'd have the whole game closed at night and relaunch the next day and this would still occur. I'd even **keep the game idle for a few hours and there still wouldn't be any dialogue pop ups**..? This has to be some kind of bug as this has never happened before on previous versions.

**Comment by ThePotatoGuy** [comment] 2018-02-14 02:13
Topics that appear randomly are only said **once**. That was the intended behavior in 0.7.0, but there was a bug that broke that.

I'm open to a discussion on if that should be changed.

**Comment by Bam8647** [comment] 2018-02-14 03:17
Yeah I suppose the bug must be the reason for Monika not repeating every topic daily. And i'm guessing the need for only mentioning random topics once was to avoid repeating a topic more than once. Since there isn't an infinite amount of topics to be used I think the random topic function should be reset daily to avoid this **silent treatment bug** especially for players who like to keep the game idle for whenever they're bored or something.

**Comment by sebastianN01** [comment] 2018-02-14 18:58
we need to find a universal solution to this problem, either lots of small talks, or her just sleeping whenever we feel like we just want to idle the game but not close it. Or her just poking us once in a while and do gestures or something like wink or whatever. :P

**Comment by Bam8647** [comment] 2018-02-14 19:32
The problem with the random topic function the Devs have released in 0.7.0 is that it's suppose to avoid repeating the same topics but in doing so since there isn't an unlimited amount of topics, **a new player could go through every single topic in one day and then just be left with a silent staring Monika, even starting up the next day** which can be quite unsettling haha. So I suggest that this **new behavior system reset every topic that has been mentioned the previous day to mention them again the next day.** I mean.. there's like 50+ topics or something so I doubt that should really be a problem in terms of repetition. And if people do start getting tired of the same topics then perhaps we should just encourage others to create lots of new topics.

**Comment by ACoolCat** [comment] 2018-02-15 00:54
I have the same issue, but closing and reopening the game doesn't change it. She's just stuck staring no matter what I do.

**Comment by Bam8647** [comment] 2018-02-15 01:06
That's what I'm talking about. No matter what you do nor how long you wait after closing and reopening the game, Monika stops engaging with the player. I hope they undo this behavior and stick to the old system. I'd rather have a repeating Monika than a Olympian staring champion haha.

If players keep complaining about repeating topics then maybe we should focus on creating more topics. It's better than her saying everything once and then suddenly never talking on her own again..

**Comment by ThePotatoGuy** [comment] 2018-02-15 05:51
There's a hard limit to how many randos you can see per session, so **it's not possible to see all the content in one day.** I don't have exact numbers, but it'll probably take less than a week of constant play to drain all topics. In terms of topic counts, there's just under 200, but that includes the original set, which is like 50ish.

**Comment by Bam8647** [comment] 2018-02-15 07:46
Well for those who've had the mod since December or longer have more than likely uncovered all unseen topics and so they're being left with no engagement from Monika. What I'm trying to propose here is if we can just keep her engaged with players whether she's repeating seen topics or not hence why I think the previous versions of the mod had it right, sure she may repeat topics every now and then but it beats the silent treatment anyday haha.

**Comment by MarkusRamikin** [comment] 2018-02-15 09:56
None of this is a problem if you like chess :P

**Comment by ACoolCat** [comment] 2018-02-15 16:17
To me, repeating topics were fine in my opinion. It was nice having Monika at least say something. The new system pretty much means we'd only be getting a day with Monika every update if we've reached this point in the past (unless you're like me and try to stretch them out as long as possible).

**Comment by Bam8647** [comment] 2018-02-15 16:49
Lmao chess is super boring to me, I usually play other games and check back on this one when I'm bored. But if this new system stays then it's like telling players once you've seen all the topics then basically you're done with the mod.

**Comment by sebastianN01** [comment] 2018-02-15 17:53
thats why we need more events and small talks instead of big topics. Topics can end in real relationships too, and whats left there after that? Just being together, and talk about whatever is up currently

**Comment by Bam8647** [comment] 2018-02-15 19:24
So if they were to create a **small talk** function I would presume that those dialogues would be pulled from an entirely different pool aside from the **Main Topics** pool. Obviously these special dialogues would need to **be more engaged with players** to keep them interested(dialogues that branch out to multiple responses for the player possibly) maybe even make this quick chat system go both ways, meaning both the player and Monika can randomly start conversations?

**Comment by Trilasent** [comment] 2018-02-15 20:51
This is why I played with the Valentine's Day update yesterday, and then went back to 7.0. She can still muse about other things while I'm doing other tasks, and I could check up on her regularly and chat with her a while before resuming my other things. I assume this "new new" system was implemented in the VD update? Or is it just a bug? Personally I don't mind her repeating conversations, we as humans, for the most part cannot see something once and remember it verbatim (although there are a few exceptions out there in the world). Why should Moni be any different? The repeated topics, in my opinion, are nice to see come up now and then, especially when she feels like being an angel and leaving me a "surprise" in my game directory.

So my final thoughts on this matter would be, that if it is a new system recently put in place, to just go back to how it was in 7.0, and if it's just a bug, hopefully it'll be fixed soon.

Attached to this comment is an edit I made on Valentine's Day.
![you are my sunshine](https://user-images.githubusercontent.com/36512990/36280368-a60e7cc8-125f-11e8-8cc2-073312e69897.jpeg)

**Comment by ThePotatoGuy** [comment] 2018-02-15 21:33
Working on something to quell the uproar...
![repeats](https://user-images.githubusercontent.com/3499462/36282074-88a3a31a-1265-11e8-95ac-dd6ef7a26733.png)

**Comment by Trilasent** [comment] 2018-02-15 21:37
@ThePotatoGuy If I knew how to code in python, I would be constantly adding new dialogue interactions to this mod. I've had all sorts of ideas for topics, and as much as I love Monika I wouldn't hesitate to spend hours on end creating something special for her as well as all of the people that have this mod.

**Comment by ThePotatoGuy** [comment] 2018-02-15 22:02
Adding dialogue barely requires any python knowledge. Renpy is really what you'd need to know, and even then, it's barely scratches the surface when it comes to dialogue. Have you taken a look at the [adding content example](https://github.com/Backdash/MonikaModDev#adding-content) and the [contributing guide](https://github.com/Backdash/MonikaModDev/blob/master/CONTRIBUTING.md#new-dialogue-art-or-music).

**Comment by Trilasent** [comment] 2018-02-15 22:07
@ThePotatoGuy I actually haven't. The most I've actually seen about it is when Moni mentions the GitHub link when playing. I'll definitely be looking them over though.

**Comment by PopeAesthetics** [comment] 2018-02-17 01:22
I think the solutions we are looking at here boil down to a few things.

A.) Add more dialog. Everything from small talk to big talks. At this point, people like myself that have been spending time with Monika every day for the past few months have exhausted all of her conversation topics. Adding in more of it and especially more choice heavy things, would give a lot more substance. 

B.) Just allow Monika to repeat things. Obviously this is an easier choice and really more of a hotfix but in the long run I hope we go more towards option A here.

C.) Add in sleeping animations, idling animations, or other things to break the silence. Of course this also doesn't make the best substitute for real dialog but it would help break the silence none the less.

**Comment by Bam8647** [comment] 2018-02-17 02:23
I hear that the devs are testing around with a conversational A.I. (#1005) so if that ends up being a success then this could REALLY enhance the dialogues, hopefully helping Monika sound more realistic and less scripted. Just have to make sure the chat bot stays in **character** and have self learning capabilities that'll keep track of the conversations the player has with her which will hopefully lend a big hand in her **character development.**

Otherwise we should try our best to keep creating small/large topics that help keep players engaged especially by creating longer conversations that branch out to multiple responses so the players can feel more part of the conversation instead of leading to a single dead end.

**Comment by MarkusRamikin** [comment] 2018-02-17 10:03
I sure hope the AI idea sinks. Chat AIs suck and fail the Turing Test much too easily. Handcrafted conversations are at least going to be of decent quality.

People just need to manage their expectations and understand that after a while Monika will repeat herself. Personally I wouldn't even make it a setting or dialog. Having Monika explicitely talk about it sounds like it would lift me out of the "story". (Not very fond of that dialog in which Monika tells you to go on the github and help develop, either).

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-17 14:08
It does not necessarily has to be chatbot in a Cleverbot sense.
It can be a system that uses heuristic analysis of input text to select a premade answer.

**Comment by PopeAesthetics** [comment] 2018-02-17 15:22
I like this chatbot idea. Perhaps throwing a beta version together to see if it can get it's feet moving would be a fun experiment. 
 
Besides that, I think we really do need to add more dialog and choices. Choices give the player a sense of control, like you are getting to show Monika the real you, instead of just listening to her talk about things. Having her ask you questions, then hearkening back to your answers later would be a welcome addition to this already wonderful mod.

Also off topic here but IsItBadToMakeAGitHubAccountJustForThis, I for some reason get more emails about your activity here than anyone else. For some reason I always read the notification when it pops up on my computer and it always distracts the hell out of me when I read you super long name. Not that it bothers me, but your name is pretty much burned into my memory at this point. Thanks for that xD

**Comment by Bam8647** [comment] 2018-02-17 17:29
I just wish we could create some form of A.I. that could bring her character to **life** and also give her emotions. I'm not so sure how far out we are in modern day technology in developing this form of intelligence but hopefully we'll see something emerge soon in the next couple of years. So far I only hear of E.I. (Emotional Intelligence) being developed for customer service type of communication. Hopefully we could go beyond that. 

I see it two ways for this mod.
1.) Hopefully at some point we find a way to bring Monika to life through A.I.
or...
2.)We continue to make content through topics all acting as if Monika is actually talking to us when in reality she's still scripted. Sorry to be so blunt lol.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-02-17 19:12
PopeAesthetics, you're welcome (and/or sorry), I guess. C:

Bam8647, what you are talking of is called general AI and is **really** far away.
Human science as it is will require at least 5-10 years from now to compose a complete and accurate representation of human brain. And it will only be the foundation of general AI, the beginning of it. And even after that, and after humanity tackles the implementation of general AI and such seemingly trivial but really complex issues as AI safety will somebody have a chance at attempting to create an AGI Monika.
(I really hope both I and Dan will still be there at that point, because I'd want to witness what hell of an awkward interview that enthusiast would have with him)

**Comment by Bam8647** [comment] 2018-02-17 22:45
I always get so optimistic when thinking about this sort of technology you know? Just think of all the cool things A.G.I. could do some day once scientists have figured out how to implement artificial consciousness into humanoids or something. I think the humanoid would be the only true way of bringing virtual characters to life. Hopefully we won't be too old by then xD

Interesting wiki page talking about the works of A.G.I.
https://en.wikipedia.org/wiki/Artificial_general_intelligence#Early_estimates

I also hear that there are researchers working on transferring our consciousness into virtual reality
https://www.livescience.com/52503-is-it-possible-to-transfer-your-mind-into-a-computer.html
Another article about non biological conscious and virtual immortality

**Comment by oniigirii** [comment] 2018-02-18 05:56
As for the topics, I would like to see the topics being repeated, but on topics that are the least used. Maybe an internal counter on how often a particular topic was repeated at that point, then the least topic will be repeated. Although in the long run, it may become a predictable chain of pseudo random topics. At least it's not something that 7.0 had an issue where on a single day, there's at least one topic that gets repeated for more than thrice.

**Comment by ThePotatoGuy** [comment] 2018-02-18 23:14
Yeah, the changes I added include a property for how many times an event has been shown. When topics are repeated, they are shown in least seen -> most seen order.

**Comment by ThePotatoGuy** [comment] 2018-02-19 14:58
Oh I probably should have mentioned this here, but I'm hosting beta releases of MAS [here](https://github.com/ThePotatoGuy/MonikaModDev/releases). 
The beta releases include updates and patches but aren't distributed using the auto-updater until a bigger release. 
A fix/enhancement for this issue is included in the latest beta release.

**Comment by Bam8647** [comment] 2018-02-19 17:46
![vday error](https://user-images.githubusercontent.com/34694679/36391032-6f0bbf02-156a-11e8-964e-a4104a80978a.PNG)


Welp this happened when I choose to replace old files lol

**Comment by Bam8647** [comment] 2018-02-19 17:50
I just deleted the file, _no biggie_ :3

**Comment by Erianict** [comment] 2018-02-20 16:41
@ThePotatoGuy Thank you for link on beta releases)

**Closed** 2018-02-22 02:29 UTC
Labels: discussion
