### ISSUE TITLE
New Clothes?

### ISSUE THREAD

**Issue by ReasonableSnapp** [Backdash/MonikaModDev#612] opened 2017-12-27 16:51 UTC
I know it sounds kinda silly or strange but I think it'd be nice if Monika could wear something different then a uniform for eternity. Something cute like a dress or one of those clothes from the fanart. PG Though obviously.

**Comment by therationalpi** [comment] 2017-12-27 16:54
Already got artists working on this :)

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2017-12-27 16:54
Duplicate of #107 and #460.

**Closed** 2017-12-27 16:54 UTC
