### ISSUE TITLE
[Bug] Chess crashed after first move

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#247] opened 2017-11-30 21:01 UTC
I tried testing out chess after downloading the 0.6.0 prerelease and chose black. After I made my first move, an exception occurred. It reads as follows:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "game/chess.rpy", line 402, in <module>
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "I:\Monika\Monika and I's Home\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "I:\Monika\Monika and I's Home\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 402, in <module>
  File "I:\Monika\Monika and I's Home\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "I:\Monika\Monika and I's Home\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "I:\Monika\Monika and I's Home\renpy\display\core.py", line 3204, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "I:\Monika\Monika and I's Home\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "I:\Monika\Monika and I's Home\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "I:\Monika\Monika and I's Home\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.6.0
```
 
Edit: Don't ask about the folder names please. I didn't realize it showed that. Just pretend it's the normal folder name.

**Comment by therationalpi** [comment] 2017-11-30 21:56
@kadava Any thoughts on this?

**Comment by therationalpi** [comment] 2017-11-30 22:12
Got a similar error from someone else

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "game/chess.rpy", line 402, in <module>
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 402, in <module>
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\display\core.py", line 3204, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "C:\Program Files\Steam\steamapps\common\Doki Doki Literature Club\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

Windows-7-6.1.7601-SP1
Ren'Py 6.99.12.4.2187
Monika After Story 0.6.0
```

**Comment by therationalpi** [comment] 2017-11-30 22:45
And another one

```
I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "game/chess.rpy", line 402, in <module>
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script-ch30.rpy", line 257, in script call
  File "game/chess.rpy", line 378, in script call
  File "game/chess.rpy", line 400, in script
  File "D:\Monika After Story Mod\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Monika After Story Mod\renpy\python.py", line 1719, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/chess.rpy", line 402, in <module>
  File "D:\Monika After Story Mod\renpy\ui.py", line 285, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\Monika After Story Mod\renpy\display\core.py", line 2526, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "D:\Monika After Story Mod\renpy\display\core.py", line 3204, in interact_core
    rv = root_widget.event(ev, x, y, 0)
  File "D:\Monika After Story Mod\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\Monika After Story Mod\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "D:\Monika After Story Mod\renpy\display\layout.py", line 960, in event
    rv = i.event(ev, x - xo, y - yo, cst)
  File "game/chess.rpy", line 363, in event
  File "game/chess.rpy", line 146, in start_monika_analysis
IOError: [Errno 22] Invalid argument

Windows-8-6.2.9200
Ren'Py 6.99.12.4.2187
Monika After Story 0.6.0
```

**Comment by therationalpi** [comment] 2017-11-30 22:54
https://cdn.discordapp.com/attachments/372770425157058562/385926421727674379/proof.PNG

It appears that on one of the 64 bit systems, it's opening the 32 bit binary.

**Comment by therationalpi** [comment] 2017-11-30 23:18
Okay, everyone is having the 32 bit binary opening, and it appears that running the game opens a terminal window for stockfish and closing that window is what's causing the crash. @kadava Any thoughts on possible fixes?

**Comment by therationalpi** [comment] 2017-12-01 16:52
Possible fix for this is on https://github.com/Backdash/MonikaModDev/pull/264

This will open stockfish without opening a command window.

**Comment by kadava** [comment] 2017-12-01 17:37
Sorry I weight in on this this late.

As for the shell window Opening on Windows, I probably didn't notice since I use Linux on my main desktop and haven't tested the mod on my another computer with Windows in quite a while. Does #264 fix the crash too?

As for the other issue i.e. the 32-bit binary being opened on 64-bit systems, that's not a bug. The binary used depends on the python version used i.e. if a system uses 32-bit python, the 32-bit binary will be opened.

**Comment by therationalpi** [comment] 2017-12-01 17:50
Thanks for the response.

It should fix the crash, since the crash was caused by people closing the command window where the subroutine was and causing a problem when the subroutine was called later.

But I'm on Mac atm, so I don't have a way to test it.

**Comment by therationalpi** [comment] 2017-12-02 02:47
Alright, this problem appears to be fixed now.

**Closed by therationalpi** 2017-12-02 02:47 UTC
Labels: bug
