### ISSUE TITLE
Forced topic change?

### ISSUE THREAD

**Issue by MrVavlo** [Backdash/MonikaModDev#610] opened 2017-12-27 07:05 UTC
After last update, I noticed something wrong. There's a small chance for Monika to change topic right after last one, without waiting. And it's always "about social media" topic. So... is It should be?
Last time, when i saw this, was after "cupcakes" topic (if that somehow helps...)

**Comment by NotShige** [comment] 2017-12-27 08:05
Duplicate of #578 and fixed.

**Closed** 2017-12-27 15:22 UTC
