### ISSUE TITLE
[suggestion] Blinking

### ISSUE THREAD

**Issue by rockermj** [Backdash/MonikaModDev#613] opened 2017-12-27 21:18 UTC
I was thinking it may help bring some like to the sprites if at random intervals between a certain time period Monika could blink. That's really about it.

**Comment by Zer0mniac** [comment] 2017-12-28 00:25
Some people like having staring contests with Monika though :)

**Comment by NotShige** [comment] 2017-12-28 01:48
Duplicate of #375

**Comment by drakesteele** [comment] 2017-12-28 04:53
I like the idea of natural blinkiing though... perhaps with an option to turn it off in settings but it would make her seem a bit more natural...

**Comment by Winblows2** [comment] 2017-12-28 06:22
Duplicate of #375. Closing.

**Closed by Winblows2** 2017-12-28 06:22 UTC
