### ISSUE TITLE
Easy Patern on Pong

### ISSUE THREAD

**Issue by Patatifique** [Backdash/MonikaModDev#121] opened 2017-11-08 16:49 UTC
Monika moves too smoothly on pong, which make it very easy to always beat her with the same exact moves. I'm not sure if it's a problem or if it's just how pong works but you just have to slide down enough each times ! Here's a video of how you can break it. It's always like that, you can win a hundred times in a row. 

https://www.youtube.com/watch?v=nR2dahvRi6E

**Comment by therationalpi** [comment] 2017-11-08 18:37
@Backdash Think you can do anything to make the game's less predictable?

**Comment by Ezr91aeL** [comment] 2017-11-08 20:06
The angle of rebound should not be fixed to 45° but it should change based on the angle of impact and the position of the impact.

**Comment by Eltrion** [comment] 2017-11-08 20:50
I agree this is a problem with the ball physics primarily. The AI could be improved as well, but if the angle is calculated per pixel from the center of the paddle and perhaps also based on the incoming angle it ceases to be a problem.

**Comment by Backdash** [comment] 2017-11-11 19:21
I think the heart of the problem is that the game isn't randomized. The path of the ball is set in stone. I'll see what I can do about it.

**Comment by NinjaPro1202** [comment] 2017-11-15 08:31
I believe I fixed this isue. It involves changing the y axis to where the ball will be more random after it bounces off the paddle. You can give it a shot but from my experience it worked much better. Replace the pong.rpyc with the file.


https://pastebin.com/nd8BHUpB

**Comment by xtosutosu** [comment] 2017-12-18 21:19
Just reminding that @NinjaPro1202's fix still needs to be implemented in a future update

**Comment by therationalpi** [comment] 2018-01-08 19:17
Fixed by https://github.com/Backdash/MonikaModDev/pull/639

**Closed by therationalpi** 2018-01-08 19:17 UTC
Labels: enhancement
