### ISSUE TITLE
[Suggestion] Enable music options during chess

### ISSUE THREAD

**Issue by StateOfBedlam** [Backdash/MonikaModDev#330] opened 2017-12-08 04:03 UTC
As far as I can tell, currently you have to commit to whatever song (or lack thereof) you choose before you initiate a game of chess. It would be nice if those options were accessible during the game.

**Comment by ThePotatoGuy** [comment] 2017-12-08 04:22
Unfortunately, the chess mode breaks/interrupts alot of the renpy user interactions (Like the game menu, for example). Getting the music selector available during the game would require a bit of an overhaul. While we won't rule it out, its of low priority due to the potential changes.

**Comment by StateOfBedlam** [comment] 2017-12-08 04:25
Okay. It's very minor, but it was worth bringing up at least once.

**Comment by avocadianmage** [comment] 2017-12-08 04:37
I was actually working on a fix for this right now, as I too wanted to change music while playing chess.

It seemed to be as simple as deleting 
```
$ songs.enabled = False
$ hkb_button.enabled = False
```

at the start `label pick_a_game` in script-ch30.rpy

as well as removing `suppress_overlay` in chess.rpy

It seems to work fine in terms of interactions with the main menu. Pressing esc to access the main menu already isn't available when playing chess, but the accessing the music menu seems to work fine with the above changes. However, please let me know if there are other test cases I should be trying/other reasons this would break.

**Comment by ThePotatoGuy** [comment] 2017-12-08 04:54
Well, yes that would be a quick fix to get music changed during chess, but there's actually a deeper issue regarding `context` that breaks the music menu. Basically if you changed the music during chess, when you finish the chess events and go back to regular flow, the music will revert back to what it was before chess. This is due to the `call_in_new_context` call in the `pick_game` function.

And unfortunately, `call_in_new_context` is required in the current way games are launched/played. The overhaul that I mentioned above would be to rewrite the games so they no longer require a new context, which would allow the music menu to work properly during those games.

So until that occurs, the workarounds are going to remain in place.

**Comment by avocadianmage** [comment] 2017-12-08 05:10
Thanks for elaborating. For whatever reason, I'm not able to reproduce that behavior. Can you try [my fork](https://github.com/avocadianmage/MonikaModDev/commit/b9c4a4b85a37607c9068cf798645e439951ad1ca)?

Workflow:
Game starts with 'Just Monika' playing
Click Play and select Chess. I chose to play as Black.
Once the board is drawn and the game starts, make a few moves
Click Music and select a different song. I chose 'Your Reality'
Make a few more moves
Double-click the King to surrender
When asked to play again, choose No
I continued to play the game after that (initiated some dialog via Talk) but the music did not switch back to 'Just Monika', it remained as 'Your Reality', which was selected while playing chess.

I'm on Linux right now, if that helps.

**Comment by avocadianmage** [comment] 2017-12-08 05:26
Re: your edit. I'm not seeing that behavior either. The chess board no longer appears when the music menu is open and I tried interacting with it as it was "invisible" but wasn't able to.

Here is my screen while accessing the music menu while playing chess:
![image](https://user-images.githubusercontent.com/8469306/33752192-e6eb19fe-dba5-11e7-8130-4101524e59b6.png)
I wasn't able to interact with the chess board while on this menu.

**Comment by ThePotatoGuy** [comment] 2017-12-08 05:31
Hm, well it seems that the flow for playing a game has changed since the last time I looked at it. Originally we had `returns` at the end of the game labels which were appropriate with `call_in_new_context`. Now its a jump.

In that case, I'd like you to change one thing to your fork and test it out. In the `pick_game` function, replace `call_in_new_context` with `call` and see if both games work normally and end normally.

Regarding overlay, that was my guess on what the parameter might be for, but I guess I was wrong. I didn't write the chess code.

**Comment by avocadianmage** [comment] 2017-12-08 05:39
Made that change and everything still seemed to work okay.

Played both games, switched music during chess (I didn't allow switching during pong), talked with Monika in between, etc. Any other specific test cases you wanted me to try with this change?

Otherwise, I can go ahead and submit the pull request if you're cool with it.

**Comment by ThePotatoGuy** [comment] 2017-12-08 05:41
Submit the pull req. I'll run additional tests. 

Good work.

**Comment by avocadianmage** [comment] 2017-12-08 05:47
Thanks, submitted.

**Comment by Winblows2** [comment] 2017-12-08 15:12
Closing because all discussion pertaining to this should now be on the open pull request. Great suggestion @avocadianmage !

**Closed by Winblows2** 2017-12-08 15:12 UTC
