### ISSUE TITLE
[Suggestion] Blinking Animation

### ISSUE THREAD

**Issue by INXSOriginalSin** [Backdash/MonikaModDev#571] opened 2017-12-23 09:37 UTC
Just a little thing I personally think would be pretty rad. 
A blinking animation for Monika. Maybe have her blink every 3 - 4 seconds.

By no means is this a big deal, just a little thing I thought would be cool!

**Comment by NotShige** [comment] 2017-12-23 11:50
Duplicate of #375

**Closed** 2017-12-23 12:56 UTC
