### ISSUE TITLE
[Bug] - Text Entry Lockup

### ISSUE THREAD

**Issue by arklistener** [Backdash/MonikaModDev#729] opened 2018-01-11 06:35 UTC
I'm not entirely sure what causes this, but on my system, sometimes when I go to talk to her, the enter button doesn't work whenever I press it. I've found that clicking out of the window and back into it while pressing enter at the same time seems to solve the issue, but only for that one text entry, as if I try to perform the same task normally afterwards, it continues to have the problem.

**Comment by IsItBadToMakeAGitHubAccountJustForThis** [comment] 2018-01-11 06:40
Duplicate of #272.

**Comment by ThePotatoGuy** [comment] 2018-01-11 14:37
Closing because of the same reason described in the duplicate issue.

**Closed by ThePotatoGuy** 2018-01-11 14:37 UTC
