### ISSUE TITLE
Minor issue during names dialogue

### ISSUE THREAD

**Issue by Authrix** [Backdash/MonikaModDev#580] opened 2017-12-25 00:45 UTC
I think this has been mentioned a while back, but just in case it wasn't or it slipped through the cracks:

During the dialogue about names (where Monika tells you about her name's meaning), she'll mention how she likes the player's in-game name but prefers their "real name". In cases where the names are the same, this comes across quite weird. Perhaps a line could be put in for this occurrence?

Image provided for clarity. 
![please excuse the drunken trackpad drawing](https://user-images.githubusercontent.com/34550378/34329965-29e09d88-e90c-11e7-85e6-754ec55da2bc.png)

**Comment by NotShige** [comment] 2017-12-25 01:01
Duplicate of #531

**Closed** 2017-12-25 01:18 UTC
