### ISSUE TITLE
[Suggestion and Bug] Improved Skip and Text Speed

### ISSUE THREAD

**Issue by Guardianvoir** [Backdash/MonikaModDev#127] opened 2017-11-10 00:37 UTC
Currently, the skip button quickly scrolls the the already read dialogue, but if left on it will keep going and skip whatever timer makes the dialogue appear until you see something new. What if instead this button could be re-purposed to skip the current topic immediately and then turn itself off? That way it could make skipping through topics Monika already used a lot easier.

As for text speed, right now it doesn't matter where the slider is positioned. The text will always appear at the same speed.

**Comment by therationalpi** [comment] 2017-11-10 01:00
As for the skip button. Being able to skip at all is a bug that will hopefully be fixed in 0.5.1, so improving the skip button isn't in the cards.

For the text speed, Monika overrides your text speed. Intended behavior.

**Closed by therationalpi** 2017-11-10 01:00 UTC
