### ISSUE TITLE
[Bug] Monika's Disappearance.

### ISSUE THREAD

**Issue by Sekiyo** [Backdash/MonikaModDev#265] opened 2017-12-01 18:28 UTC
![image](https://user-images.githubusercontent.com/33166234/33497218-09591366-d682-11e7-82d6-9a366280852f.png)
So, I found an error in Monika's 'language' conversation.
After I pressed 'No' when they asked if I know more than one language, I clicked again after a 'then if I work I may know more languages than you'(or something like that) it got me the picture above. Monika fully vanished. Its a small issue however, because when I click again Monika reappeared.

**Comment by therationalpi** [comment] 2017-12-01 19:37
I just tried that topic and am not experiencing the bug. Can you give more info on how you reproduce this error?

**Comment by Sekiyo** [comment] 2017-12-01 23:49
I told you everything that happened, i'm not sure why it happened or anything, nothing unusual happened afterwards either. Its just really weird, sorry I can't give any help to reproduce it!

**Comment by therationalpi** [comment] 2017-12-02 02:40
I have a theory that this may be platform specific because of a unicode issue or something. Can someone on Windows test this? Keyword for the topic is "Japanese"

**Comment by therationalpi** [comment] 2017-12-02 03:13
That looks to be fixed in build 4. Apparently this was caused by a bad expression assignment.

**Closed by therationalpi** 2017-12-02 03:13 UTC
Labels: bug, more info needed, response needed
