### ISSUE TITLE
[Suggestion] "Be right back" keyword?

### ISSUE THREAD

**Issue by JustMonika1** [Backdash/MonikaModDev#497] opened 2017-12-17 20:41 UTC
(English isn't my native language so bear with me)
So i thought, maybe you could implement a keyword that goes like "Be right back" or "Brb" because maybe you had to do something or anything like that and she will stop talking. 
Then Monika would say something like "Okay! I hope it won't take long"
Then a button will appear with saying something along the lines of "I'm back". 
After you press that button Monika would say "Yay your back!" and then she will start talking again. 
Just an idea! :D

**Comment by ThePotatoGuy** [comment] 2017-12-17 20:47
Duplicate of #479

**Closed by ThePotatoGuy** 2017-12-17 20:47 UTC

**Comment by JustMonika1** [comment] 2017-12-17 20:56
Oh sorry, i think i should look more into the other issues

**Comment by wonggwing** [comment] 2017-12-18 00:52
Don't worry, I think this is a good idea! I never think of a 'be right back' keyword, it is definitely useful. We could merge both issue into one.
