### ISSUE TITLE
Outside World [suggestion]

### ISSUE THREAD

**Issue by JustMonikaMkay** [Backdash/MonikaModDev#883] opened 2018-01-31 11:18 UTC
So what if you and monika can go Shopping like she said ... i can do some art work but i will need the sprites of her do i can do work :T 
There should be something like : 
Go to a cafe with monika
Go shopping with monika
Go to an arcade with monika ?
Go to a karaoke with monika etc.
I will help with backgrounds and and some sprites for clothing but i i will need her normal sprites ...
(sorry if this has been suggested already ...)

**Comment by therationalpi** [comment] 2018-01-31 18:41
Outside world stuff is difficult because the setting outside of the spaceroom hasn't been established yet.

Regardless, closing this suggestion as a duplicate of previous suggestions.

**Closed by therationalpi** 2018-01-31 18:41 UTC
Labels: art, suggestion
