### ISSUE TITLE
how to update the game?

### ISSUE THREAD

**Issue by jeevis** [Backdash/MonikaModDev#456] opened 2017-12-15 02:03 UTC
Before I downloaded 0.62, the game say no updates needed. After I download ver 0.62 but did not place it in the game's folders, they just straight away let me into the app without asking. Is it updated?

**Comment by Winblows2** [comment] 2017-12-15 02:48
So, let me try and explain this... 
You can check for updates via the Settings menu, and if you did not place the new update in the /game folder, it wouldn't be updated.

My suggestion: Go to the Settings menu on 0.6.1 and check for updates there, it should say an update is available.

**Comment by ThePotatoGuy** [comment] 2017-12-15 03:26
Duplicate of issue #419 

Closing

**Closed by ThePotatoGuy** 2017-12-15 03:26 UTC
Labels: duplicate
